# Generated by Django 3.1.7 on 2021-04-08 14:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Please enter your name.', max_length=30, verbose_name='Name : ')),
                ('text', models.TextField(verbose_name='Content')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Create DateTime')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myblog.post', verbose_name='Article Name')),
            ],
        ),
    ]
