# Generated by Django 3.1.7 on 2021-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anon', max_length=30, verbose_name='Name : '),
        ),
    ]
